target("ping")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/ping.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("chat")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/chat.cpp")
    add_files("../third_party/linenoise/linenoise.c")
    add_includedirs("../third_party/linenoise")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("bench")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/bench.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("ppl")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/ppl.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("batch_bench")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/batch_bench.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("serve")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/serve.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()
