target("ping")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/ping.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()

target("chat")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/chat.cpp")
    set_rundir("$(projectdir)")
    add_packages("readline")
    on_install(function (target) end)
target_end()

target("bench")
    set_kind("binary")
    add_deps("zedinfer")
    add_files("../examples/bench.cpp")
    set_rundir("$(projectdir)")
    on_install(function (target) end)
target_end()