target("tokenizer")
    set_kind("static")
    add_packages("icu4c", {public = true})
    add_files("../src/frontend/tokenizer/*.cpp")
    on_install(function (target) end)
target_end()

target("sampler")
    set_kind("static")
    add_files("../src/frontend/sampler/*.cpp")
    on_install(function (target) end)
target_end()

target("loader")
    set_kind("static")
    add_files("../src/frontend/loader/*.cpp")
    on_install(function (target) end)
target_end()

target("models")
    set_kind("static")
    add_deps("loader")
    add_files("../src/frontend/models/*.cpp")
    on_install(function (target) end)
target_end()

target("graph")
    set_kind("static")
    add_deps("models")
    add_files("../src/frontend/graph/*.cpp")
    on_install(function (target) end)
target_end()