target("test-tokenizer")
    set_kind("binary")
    set_group("test")
    add_deps("tokenizer", "zedinfer")
    add_files("../tests/tokenizer/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-loader")
    set_kind("binary")
    set_group("test")
    add_deps("utils")
    add_deps("loader")
    add_files("../tests/loader/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-models")
    set_kind("binary")
    set_group("test")
    add_deps("zedinfer")
    add_files("../tests/models/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-qwen3-5-config-parse")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_deps("zedinfer")
    add_files("../tests/models/test_qwen3_5_config_parse.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-qwen3-5-weight-name-map")
    set_kind("binary")
    set_group("test")
    add_files("../tests/models/test_qwen3_5_weight_name_map.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-ssm-state-pool")
    set_kind("binary")
    set_group("test")
    add_files("../tests/models/test_ssm_state_pool.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-hybrid-forward-config")
    set_kind("binary")
    set_group("test")
    add_files("../tests/models/test_hybrid_forward_config.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-qwen3-5-load")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/integration/test_qwen3_5_load.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-memorypool")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_memory_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-storage")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_storage.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-tensor")
    set_kind("binary")
    set_group("test")
    add_deps("tensor")
    add_files("../tests/tensor/test_tensor.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-blockpool")
    set_kind("binary")
    set_group("test")
    add_deps("kvcache")
    add_files("../tests/kvcache/test_block_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-prefixcache")
    set_kind("binary")
    set_group("test")
    add_deps("kvcache")
    add_files("../tests/kvcache/test_prefix_cache.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-sampler")
    set_kind("binary")
    set_group("test")
    add_deps("sampler", "ops", "ops-cpu", "tensor", "core", "device", "device-cpu", "utils")
    add_files("../tests/sampler/test_sampler.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-chattemplate")
    set_kind("binary")
    set_group("test")
    add_deps("zedinfer")
    add_files("../tests/zedinfer/test_chat_template.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-chat-template-jinja")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_deps("zedinfer")
    add_files("../tests/zedinfer/test_chat_template_jinja.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-minja-smoke")
    set_kind("binary")
    set_group("test")
    add_files("../tests/integration/test_minja_smoke.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-stb-smoke")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/integration/test_stb_smoke.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-flashinfer-ssu-link")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    if has_config("flashinfer") then
        add_defines("USE_FLASHINFER", "FLASHINFER_ENABLE_BF16")
        add_files("../tests/integration/test_flashinfer_ssu_link.cu")
        -- Match the CUDA flags used by ops-nvidia / flashinfer_wrapper.cu so
        -- that the FlashInfer Mamba headers compile under the same toolchain.
        -- --expt-relaxed-constexpr and --expt-extended-lambda mirror FlashInfer's
        -- own JIT flags (flashinfer/jit/cpp_ext.py) — the Mamba headers call
        -- host constexpr from __device__ code and use C++20-style templated
        -- lambdas inside dispatch helpers.
        set_policy("build.cuda.devlink", true)
        set_policy("check.auto_ignore_flags", false)
        add_cugencodes("native")
        add_cxflags("-fPIC", {force = true})
        add_cuflags("-rdc=true", "-Xcompiler=-fPIC",
                    "--expt-relaxed-constexpr", "--expt-extended-lambda",
                    {force = true})
        add_culdflags("-Xcompiler=-fPIC", {force = true})
        add_syslinks("cuda", "cudart")
    else
        on_load(function () raise("test-flashinfer-ssu-link requires --flashinfer=y") end)
    end

target("test-ops-mamba-ssu")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/models/test_ops_mamba_ssu.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-ops-causal-conv1d")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/models/test_ops_causal_conv1d.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-ops-mrope-3d")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/models/test_ops_mrope_3d.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-ops-attn-output-gate")
    set_kind("binary")
    set_group("test")
    set_rundir("$(projectdir)")
    add_files("../tests/models/test_ops_attn_output_gate.cpp")
    add_deps("zedinfer")
    add_packages("gtest")
    add_syslinks("gtest_main")
