add_requires("gtest")

target("test-tokenizer")
    set_kind("binary")
    set_group("test")
    add_deps("tokenizer")
    add_files("../tests/tokenizer/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-loader")
    set_kind("binary")
    set_group("test")
    add_deps("utils")
    add_deps("loader")
    add_files("../tests/loader/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-memorypool")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_memory_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-storage")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_storage.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-tensor")
    set_kind("binary")
    set_group("test")
    add_deps("tensor")
    add_files("../tests/tensor/test_tensor.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")