add_requires("gtest")

target("test-tokenizer")
    set_kind("binary")
    add_deps("tokenizer")
    add_files("../test/tokenizer/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main") 

target("test-loader")
    set_kind("binary")
    add_deps("loader")
    add_files("../test/loader/*.cpp")
    add_files("../src/utils/types.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main") 

target("test-memorypool")
    set_kind("binary")
    add_deps("core")
    add_files("../test/core/test_memory_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-storage")
    set_kind("binary")
    add_deps("core")
    add_files("../test/core/test_storage.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main") 