target("test-tokenizer")
    set_kind("binary")
    set_group("test")
    add_deps("tokenizer", "zedinfer")
    add_files("../tests/tokenizer/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-loader")
    set_kind("binary")
    set_group("test")
    add_deps("utils")
    add_deps("loader")
    add_files("../tests/loader/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-models")
    set_kind("binary")
    set_group("test")
    add_deps("zedinfer")
    add_files("../tests/models/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-memorypool")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_memory_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-storage")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../tests/core/test_storage.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-tensor")
    set_kind("binary")
    set_group("test")
    add_deps("tensor")
    add_files("../tests/tensor/test_tensor.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-blockpool")
    set_kind("binary")
    set_group("test")
    add_deps("kvcache")
    add_files("../tests/kvcache/test_block_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-prefixcache")
    set_kind("binary")
    set_group("test")
    add_deps("kvcache")
    add_files("../tests/kvcache/test_prefix_cache.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-sampler")
    set_kind("binary")
    set_group("test")
    add_deps("sampler", "ops", "ops-cpu", "tensor", "core", "device", "device-cpu", "utils")
    add_files("../tests/sampler/test_sampler.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")
    add_syslinks("pthread")

target("test-chattemplate")
    set_kind("binary")
    set_group("test")
    add_deps("zedinfer")
    add_files("../tests/zedinfer/test_chat_template.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")
