add_requires("gtest")

target("test-tokenizer")
    set_kind("binary")
    set_group("test")
    add_deps("tokenizer")
    add_files("../test/tokenizer/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-loader")
    set_kind("binary")
    set_group("test")
    add_deps("loader")
    add_files("../test/loader/*.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-memorypool")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../test/core/test_memory_pool.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-storage")
    set_kind("binary")
    set_group("test")
    add_deps("core")
    add_files("../test/core/test_storage.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-tensor")
    set_kind("binary")
    set_group("test")
    add_deps("tensor")
    add_files("../test/tensor/test_tensor.cpp")
    add_packages("gtest")
    add_syslinks("gtest_main")

target("test-demo")
    set_kind("binary")
    set_group("test")
    add_deps("engine")
    add_files("../test/test_demo.cpp")

-- target("test-inference")
--     set_kind("binary")
--     set_group("test")
--     add_deps("engine")
--     add_files("../test/test_inference.cpp")
--     add_packages("gtest")
--     add_syslinks("gtest_main")  