// Unit test for ops::mrope_3d — verifies the GPU kernel matches a golden
// reference (generated by tests/fixtures/mrope_3d/gen_reference.py) at bf16
// precision. The fixture mirrors Qwen3.5's softmax-attention layer config:
//   head_dim=256, partial_factor=0.25 -> Dh_rot=64, half=32,
//   section=[11,11,10], theta=1e7, interleaved pair layout.
//
// Pass criterion: max abs diff (bf16) < 0.01, AND the pass-through dims
// [Dh_rot, head_dim) are bitwise unchanged.

#include "backend/core/context/context.hpp"
#include "backend/device/device.hpp"
#include "backend/ops/mrope/mrope_3d.hpp"
#include "backend/tensor/tensor.hpp"
#include "frontend/models/hybrid_forward_config.hpp"

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <gtest/gtest.h>
#include <string>
#include <vector>

namespace {

#if defined(ENABLE_NVIDIA_API)

using zedinfer::Tensor;
using zedinfer::core::context;
using zedinfer::ops::mrope_3d;

// Skip whole suite if no NVIDIA runtime can be initialized (e.g. headless CI).
class OpsMrope3d : public ::testing::Test {
protected:
    void SetUp() override {
        try {
            context().setDevice(ZEDINFER_DEVICE_NVIDIA, 0);
        } catch (const std::exception& e) {
            GTEST_SKIP() << "NVIDIA runtime init failed: " << e.what();
        }
    }
};

// Read whole binary file into a buffer of N bytes; returns false on miss/size mismatch.
bool read_exact(const std::string& path, void* dst, size_t bytes) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return false;
    in.read(reinterpret_cast<char*>(dst), static_cast<std::streamsize>(bytes));
    return in.gcount() == static_cast<std::streamsize>(bytes);
}

float bf16_to_float(uint16_t v) {
    uint32_t u = static_cast<uint32_t>(v) << 16;
    float f;
    std::memcpy(&f, &u, sizeof(f));
    return f;
}

TEST_F(OpsMrope3d, MatchesPythonReference) {
    // Fixture layout (generated by tests/fixtures/mrope_3d/gen_reference.py):
    //   x_in.bin       : bf16 [N, H, Dh]    = 5 * 2 * 256 * 2  = 5120 bytes
    //   x_out_ref.bin  : bf16 [N, H, Dh]    = 5120 bytes
    //   pos_thw.bin    : int32 [3, N]       = 3 * 5 * 4        = 60 bytes
    constexpr int N  = 5;
    constexpr int H  = 2;
    constexpr int Dh = 256;
    constexpr float partial_factor = 0.25f;
    constexpr int Dh_rot = static_cast<int>(Dh * partial_factor); // 64

    const std::string fixture_dir = "tests/fixtures/mrope_3d/";
    std::vector<uint16_t> x_host(static_cast<size_t>(N) * H * Dh);
    std::vector<uint16_t> ref_host(static_cast<size_t>(N) * H * Dh);
    std::vector<int32_t>  pos_host(3 * N);

    if (!read_exact(fixture_dir + "x_in.bin",       x_host.data(),   x_host.size()   * sizeof(uint16_t)) ||
        !read_exact(fixture_dir + "x_out_ref.bin",  ref_host.data(), ref_host.size() * sizeof(uint16_t)) ||
        !read_exact(fixture_dir + "pos_thw.bin",    pos_host.data(), pos_host.size() * sizeof(int32_t))) {
        GTEST_SKIP() << "mrope_3d fixtures missing or wrong size; "
                     << "regenerate via `python3 tests/fixtures/mrope_3d/gen_reference.py`";
    }

    auto x   = Tensor::create({static_cast<size_t>(N), static_cast<size_t>(H), static_cast<size_t>(Dh)},
                              ZEDINFER_DTYPE_BF16, ZEDINFER_DEVICE_NVIDIA, 0);
    auto pos = Tensor::create({3, static_cast<size_t>(N)},
                              ZEDINFER_DTYPE_I32, ZEDINFER_DEVICE_NVIDIA, 0);

    auto* api = zedinfer::device::getRuntimeAPI(ZEDINFER_DEVICE_NVIDIA);
    api->memcpy_sync(x->data(),   x_host.data(),   x_host.size()   * sizeof(uint16_t), ZEDINFER_MEMCPY_H2D);
    api->memcpy_sync(pos->data(), pos_host.data(), pos_host.size() * sizeof(int32_t),  ZEDINFER_MEMCPY_H2D);

    zedinfer::model::MRoPEConfig cfg;
    cfg.interleaved    = true;
    cfg.section        = {11, 11, 10};
    cfg.partial_factor = partial_factor;
    cfg.theta          = 1e7f;

    ASSERT_NO_THROW(mrope_3d(x, pos, cfg));
    context().runtime().synchronize();

    std::vector<uint16_t> got_host(static_cast<size_t>(N) * H * Dh);
    api->memcpy_sync(got_host.data(), x->data(), got_host.size() * sizeof(uint16_t), ZEDINFER_MEMCPY_D2H);

    // 1) Numerical correctness against the Python reference (bf16 tolerance).
    float max_abs_diff = 0.0f;
    int   max_idx      = -1;
    for (size_t i = 0; i < got_host.size(); ++i) {
        const float g = bf16_to_float(got_host[i]);
        const float r = bf16_to_float(ref_host[i]);
        ASSERT_FALSE(std::isnan(g)) << "NaN in mrope_3d output at flat idx " << i;
        ASSERT_FALSE(std::isinf(g)) << "Inf in mrope_3d output at flat idx " << i;
        const float d = std::abs(g - r);
        if (d > max_abs_diff) {
            max_abs_diff = d;
            max_idx      = static_cast<int>(i);
        }
    }
    std::cout << "[ok] mrope_3d max_abs_diff=" << max_abs_diff
              << " (worst flat idx=" << max_idx << ")\n";
    EXPECT_LT(max_abs_diff, 0.01f)
        << "mrope_3d numerical drift exceeds bf16 tolerance";

    // 2) Pass-through verification: dims [Dh_rot, Dh) must be bitwise unchanged
    //    relative to the input (since the kernel writes only the rotary half).
    for (int n = 0; n < N; ++n) {
        for (int hd = 0; hd < H; ++hd) {
            for (int d = Dh_rot; d < Dh; ++d) {
                const size_t flat = (static_cast<size_t>(n) * H + hd) * Dh + d;
                EXPECT_EQ(got_host[flat], x_host[flat])
                    << "pass-through dim " << d << " changed at (n=" << n
                    << ", hd=" << hd << ")";
            }
        }
    }
}

#else // !ENABLE_NVIDIA_API

TEST(OpsMrope3d, RequiresNvidiaBackend) {
    GTEST_SKIP() << "ops::mrope_3d GPU path requires an NVIDIA backend build";
}

#endif

} // namespace
